version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: balar4022
      POSTGRES_DB: hotel_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - hotel-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: hotel_management
      JWT_SECRET: your-secret-key
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - hotel-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - hotel-network

networks:
  hotel-network:
    driver: bridge

volumes:
  postgres_data: